import { library, config } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

// Import des icônes que vous souhaitez utiliser
// Solid icons
import {
  faHome,
  faUser,
  faSearch,
  faChartBar,
  faFileAlt,
  faDownload,
  faArrowLeft,
  faArrowUp,
  faArrowDown,
  faArrowRight,
  faSun,
  faMoon,
  faInfoCircle,
  faCheckCircle,
  faExclamationTriangle,
  faTimesCircle,
  faBars,
  faTimes,
  faChevronDown,
  faChevronUp,
  faChevronRight,
  faChevronLeft,
  faExternalLinkAlt,
  faEnvelope,
  faPhone,
  faMapMarkerAlt,
  faLocationDot,
  faCog,
  faCogs,
  faEye,
  faEyeSlash,
  faEdit,
  faTrash,
  faPlus,
  faMinus,
  faSpinner,
  faCircle,
  faSquare,
  faHeart,
  faStar,
  faBuilding,
  faUsers,
  faMoneyBillWave,
  faIndustry,
  faLandmark,
  faCalendar,
  faTable,
  faPrint,
  faFilePdf,
  faFileExcel,
  faFileWord,
  faGlobe,
  faLink,
  faImage,
  faCamera,
  faBook,
  faLeaf,
  faSeedling,
  faRecycle,
  faShieldAlt,
  faShieldHalved,
  faChartLine,
  faClock,
  // Nouvelles icônes pour MOM
  faBullhorn,
  faScaleBalanced,
  faGem,
  faCoins,
  faCubes,
  faAtom,
  faPaperPlane,
  faCircleExclamation,
  faFileCircleQuestion,
  faCheck,
  faBullseye,
  // Icônes pour le back-office admin
  faChartPie,
  faFolderOpen,
  faNewspaper,
  faAnglesLeft,
  faAnglesRight,
  faRightFromBracket,
  faRightToBracket,
  faInbox,
  faLock,
  faXmark,
  faFileLines,
} from '@fortawesome/free-solid-svg-icons'

// Regular icons
import {
  faHeart as farHeart,
  faStar as farStar,
  faFile as farFile,
  faFileAlt as farFileAlt,
} from '@fortawesome/free-regular-svg-icons'

// Brand icons
import {
  faFacebook,
  faFacebookF,
  faTwitter,
  faLinkedin,
  faLinkedinIn,
  faGithub,
  faYoutube,
  faInstagram,
} from '@fortawesome/free-brands-svg-icons'

// Désactiver l'ajout automatique de CSS par Font Awesome
// (Nuxt gère le CSS différemment)
config.autoAddCss = false

// Ajouter les icônes à la bibliothèque
library.add(
  // Solid
  faHome,
  faUser,
  faSearch,
  faChartBar,
  faFileAlt,
  faDownload,
  faArrowLeft,
  faArrowUp,
  faArrowDown,
  faArrowRight,
  faSun,
  faMoon,
  faInfoCircle,
  faCheckCircle,
  faExclamationTriangle,
  faTimesCircle,
  faBars,
  faTimes,
  faChevronDown,
  faChevronUp,
  faChevronRight,
  faChevronLeft,
  faExternalLinkAlt,
  faEnvelope,
  faPhone,
  faMapMarkerAlt,
  faLocationDot,
  faCog,
  faCogs,
  faEye,
  faEyeSlash,
  faEdit,
  faTrash,
  faPlus,
  faMinus,
  faSpinner,
  faCircle,
  faSquare,
  faHeart,
  faStar,
  faBuilding,
  faUsers,
  faMoneyBillWave,
  faIndustry,
  faLandmark,
  faCalendar,
  faTable,
  faPrint,
  faFilePdf,
  faFileExcel,
  faFileWord,
  faGlobe,
  faLink,
  faImage,
  faCamera,
  faBook,
  faLeaf,
  faSeedling,
  faRecycle,
  faShieldAlt,
  faShieldHalved,
  faChartLine,
  faClock,
  // Nouvelles icônes pour MOM
  faBullhorn,
  faScaleBalanced,
  faGem,
  faCoins,
  faCubes,
  faAtom,
  faPaperPlane,
  faCircleExclamation,
  faFileCircleQuestion,
  faCheck,
  faBullseye,
  // Icônes pour le back-office admin
  faChartPie,
  faFolderOpen,
  faNewspaper,
  faAnglesLeft,
  faAnglesRight,
  faRightFromBracket,
  faRightToBracket,
  faInbox,
  faLock,
  faXmark,
  faFileLines,
  // Regular
  farHeart,
  farStar,
  farFile,
  farFileAlt,
  // Brands
  faFacebook,
  faFacebookF,
  faTwitter,
  faLinkedin,
  faLinkedinIn,
  faGithub,
  faYoutube,
  faInstagram
)

export default defineNuxtPlugin((nuxtApp) => {
  // Enregistrer le composant globalement
  nuxtApp.vueApp.component('font-awesome-icon', FontAwesomeIcon)
})
